package se.wtm.sublibra.lightControl;

/**
 * Created by jonash on 2016-12-29.
 */
public class Device {
    String deviceName;
    boolean isDimmable;
    int id;

    public Device(){

    }

    public Device(String deviceName, boolean isDimmable, int id) {
        this.deviceName = deviceName;
        this.isDimmable = isDimmable;
        this.id = id;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    public boolean isDimmable() {
        return isDimmable;
    }

    public void setDimmable(boolean dimmable) {
        isDimmable = dimmable;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Override
    /**
     * Autogenerated equals function     *
     */
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Device device = (Device) o;

        if (isDimmable != device.isDimmable) return false;
        if (id != device.id) return false;
        return deviceName != null ? deviceName.equals(device.deviceName) : device.deviceName == null;

    }

    @Override
    public String toString() {
        return "Device{" +
                "deviceName='" + deviceName + '\'' +
                ", isDimmable=" + isDimmable +
                ", id=" + id +
                '}';
    }
}
